[package]
cairo-version = "2.3.0"
name = "rollyourown"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
# cubit = {git = "https://github.com/influenceth/cubit.git"}
dojo = {git = "https://github.com/dojoengine/dojo.git"}
# dojo = {git = "https://github.com/dojoengine/dojo.git", rev = "d7f46502cba3d6462b68a4dfb07336377bca2678"}
# dojo = {git = "https://github.com/dojoengine/dojo.git", tag = "v0.3.6"}


[[target.dojo]]

[scripts]
katana = "katana --disable-fee --invoke-max-steps 999999999"
build = "sozo build && scarb run gendojo"
gendojo = "./scripts/gen.sh"
auth = "./scripts/default_auth.sh local"
auth_dev = "./scripts/default_auth.sh"
migrate = "sozo migrate && scarb run gendojo && scarb run auth"
migrate_dev = "sozo migrate --rpc-url https://api.cartridge.gg/x/ryo/katana --account-address 0x6e857786bbd1652857d673836c41e0544d9d5ecd3e7a1bbde744e328b8cc2f6 --private-key 0x5e9d85de083b7ddd3029c44de2997ceba8384074bbebb66696a1b507f0466fc"

[tool.dojo.env]
# Katana
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
rpc_url = "http://localhost:5050"

# seed 420
# account_address = "0x6e857786bbd1652857d673836c41e0544d9d5ecd3e7a1bbde744e328b8cc2f6"
# private_key = "0x5e9d85de083b7ddd3029c44de2997ceba8384074bbebb66696a1b507f0466fc"
# rpc_url = "https://api.cartridge.gg/x/ryo/katana"

[tool.dojo.world]
name = "Roll Your Own"
description = "example world"
website = "https://rollyourown.preview.cartridge.gg/"
icon_uri = "file://assets/icon.png"
cover_uri = "file://assets/cover.png"
socials.x = "https://x.com/TheDopeWars"